# Nombre del sitio
name: Include Poetry

# Título
title: Include Poetry

# Descripcón del sitio
description: Curso de preparación para las Olimpiadas de Informática, como la OMI y OMIPS

# Email
email: contacto@include-poetry.com

# Facebook
facebook:
  app_id: 201218926955149

# Autor
author: rivel_co

# Versión de Markdown
markdown: kramdown

# Google services
google_analytics: UA-74086952-1

# Base del sitio url
#url: "http://localhost:4000"
url: "192.168.1.67:4000"
baseurl: /Code
host: 0.0.0.0

# Excuidos de la conversión
exclude: 
  - Construir.bat
  - Montar.bat
  - UpAlgolia.bat
  - IP-Code.sublime-workspace
  - Development

# Algolia - buscador
algolia:
  application_id: 'QO0HGR5828'
  index_name: 'MainIndexIPC'
  files_to_exclude:
    - index.html
    - 404.md
    - Motivacion/index.html
    - Otros-temas/Karel/Tags/index.html
    - Otros-temas/C++/Tags/index.html
    - Otros-temas/C++/index.html
    - Otros-temas/Karel/index.html
    - Problemas/Resueltos/C++/index.html
    - Problemas/Resueltos/C++/Tags/index.html
    - Buscador/index.html
  nodes_to_index: 'p,ul,ol,blockquote'
  settings:
    attributesForFaceting:
      - tags
      - olimpiada
      - subject
      - author

# Variables del sitio
logo-grande-n: "/Multimedia/Logo/IPoetryN.png"
logo-chico-n: "/Multimedia/Logo/IPN.png"
logo-grande-b: "/Multimedia/Logo/IPoetryB.png"
logo-chico-b: "/Multimedia/Logo/IPB.png"
logo-pluma: "/Multimedia/Logo/RPlumaN.png"
iP-Sources: "/Code/RecursosDev"

# Colecciones
collections:
  C: 
    output: true
    permalink: /C++/:path/
  Karel:
    output: true
    permalink: /Karel/:path/
  Otros-C:
    output: true
    permalink: /Otros-temas/C++/:title/
  Otros-Karel:
    output: true
    permalink: /Otros-temas/Karel/:title/
  Resueltos-C:
    output: true
    permalink: /Problemas/Resueltos/C++/:title/
  Descargables:
    output: false